config/routes.rb
Rails.application.routes.draw do
  resources :labels, only: %i[new create destroy]
  namespace :admin do
    root "users#index"
    resources :users, except: [:index, :show]
  end
  root to: "tasks#index"
  resources :tasks, except: :index do
    get "search", on: :collection
    get "label_search", on: :collection
  end
  resources :users, only: [:new, :show, :create]
  resource :session, only: [:create, :destroy]
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :bigint           not null, primary key
#  description :text             not null
#  end_date    :datetime
#  name        :string           not null
#  priority    :integer
#  status      :string           default("yet"), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint
#
# Indexes
#
#  index_tasks_on_status   (status)
#  index_tasks_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Task < ApplicationRecord
  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings
  belongs_to :user
  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 255 }

  enum priority: {
    low: 0,
    middle: 1,
    high: 2
  }

  scope :search_subject, -> (name_arr) { where("name LIKE ?", name_arr.map{|n|"%#{n}%"})}

  STATUS_VALUES = %w("" yet started done)
  class << self
    def status_text(status)
      I18n.t("activerecord.attributes.task.status_#{status}")
    end

    def status_options
      STATUS_VALUES.map { |status| [status_text(status), status]}
    end

    def search_name(query)
      rel = order("id")
      if query.present?
        rel = rel.where("name LIKE ?", "%#{query}%")
      end
      rel
    end

    def search_status(query)
      rel = order("id")
      if query.present?
        rel = rel.where(status: query)
      end
      rel
    end
    
    def search_double(q_name, q_status)
      rel = order("id")
      if q_name.present? && q_status.present?
        rel = rel.where("name LIKE ?", "%#{q_name}%").or(rel.where(status: q_status))
      end
      rel
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :login_required
  before_action :set_task, only:[:show, :edit, :update, :destroy]

  def index
    if params[:sort_end_date] == "asc"
      @tasks = Task.order(end_date: :asc).page(params[:page]).per(5)
    elsif params[:sort_end_date] == "desc"
      @tasks = Task.order(end_date: :desc).page(params[:page]).per(5)
    elsif params[:priority_num] == "asc"
      @tasks = Task.order(priority: :asc).page(params[:page]).per(5)
    elsif params[:priority_num] == "desc"
      @tasks = Task.order(priority: :desc).page(params[:page]).per(5)
    else
      @tasks = Task.order(created_at: :desc).page(params[:page]).per(5)
    end
  end

  def search
    if params[:search][:q_name] != "" && params[:search][:q_status] =! ""
      @tasks = Task.search_double(params[:search][:q_name], 
        params[:search][:q_status]).page(params[:page]).per(5)

    elsif params[:search][:q_name] != ""
      @tasks = Task.search_name(params[:search][:q_name]).page(params[:page]).per(5)
    elsif params[:search][:q_status] != ""
      @tasks = Task.search_status(params[:search][:q_status]).page(params[:page]).per(5)
    else
      @tasks = Task.order(created_at: :desc).page(params[:page]).per(5)
    end
    render :index
  end

  def label_search
    @tasks = params[:label_id].present? ? Label.find(params[:label_id]).tasks : Task.all
    @tasks = @tasks.page(params[:page]).per(5)
    render :index
  end

  def new
    @task = Task.new
    @label = Label.new
  end

  def show; end

  def edit
    if logged_in_as_admin? || current_user.own?(@task)
      render :edit
    else
      redirect_to root_path
    end
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to root_path, notice: "「#{@task.name}」を作成しました。"
    else
      render :new
    end
  end

  def update
    @task.assign_attributes(task_params)
    if @task.save
      redirect_to @task, notice: "「#{@task.name}」を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to root_path, notice: "「#{@task.name}」を削除しました。"
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(
      :name,
      :description,
      :created_at,
      :updated_at,
      :end_date,
      :status,
      :priority,
      label_ids: [],
    )
  end
end

app/views/tasks/_form.html.slim
= render "shared/errors", obj: task

= form_with model: task, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control", id: "task_name"
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: "form-control", id: "task_description"
  .form-group
    = f.label :priority, class: "mr-2"
    = f.select :priority, Task.priorities.keys.to_a
  .form-group
    = f.label :status, class: "mr-2"
    = f.select :status, Task.status_options
  .form-group
    = f.label :end_date, class: "mr-2"
    = f.datetime_select :end_date,
        start_year: Time.current.year, end_year: Time.current.year + 10,
        use_month_numbers: true
  .form-group
    = f.label t("label")
    = link_to t("labeling"), new_label_path, class: "btn btn-outline-dark label_button"
    = f.collection_check_boxes(:label_ids, Label.where(id:1..5).or(Label.where(id: current_user.labels.ids)), :id, :name) do |label|
      .form-check.ml-3
        = label.label class: "form-check-label" do
          = label.check_box class: "form-check-input"
          = label.text
          = link_to t("delete"), label_path(label.object.id), class: "btn btn-outline-danger btn-sm ml-2", method: :delete if label.object.id > 5
  = f.submit nil, class: "btn btn-primary"

app/views/tasks/edit.html.slim
h1 = t ".title"

.nav.justify-content-end
  = link_to t(".index"), root_path, class: "nav-link"

= render "form", task: @task

app/views/tasks/index.html.slim
h1 = t ".title"

.row.mt-3.justify-content-between.align-items-center
  .col-md-4
    = link_to t(".new") , new_task_path, class: "btn btn-primary"

  .col-md-5
    = form_with scope: :search, url: search_tasks_path, method: :get, local: true do |f|
      = f.select :q_status, Task.status_options
      = f.text_field :q_name
      = f.submit t(".search")

  .col-md-3
    = form_with url: label_search_tasks_path, method: :get do
      = select_tag :label_id, options_from_collection_for_select(Label.all, :id, :name, params[:label_id]),
                    { prompt: 'ラベルで絞り込み',
                      class: 'form-control',
                      id: "search_label",
                      onchange: 'submit(this.form);' }

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th = Task.human_attribute_name("name")
      th 
        = Task.human_attribute_name("priority")
        = link_to "▲", root_path(priority_num: "asc"), class: "ml-2", id: "pri_asc"
        = link_to "▼", root_path(priority_num: "desc"), class: "ml-2", id: "pri_desc"
      th 
        = Task.human_attribute_name("status")
      th.end_date 
        = Task.human_attribute_name("end_date")
        = link_to "▲", root_path(sort_end_date: "asc"), class: "ml-2", id: "end_asc"
        = link_to "▼", root_path(sort_end_date: "desc"), class: "ml-2", id: "end_desc"
      th
  tbody
    - @tasks.each do |task|
      tr.sort
        td = link_to task.name, task_path(task)
        td = task.priority
        td = Task.human_attribute_name("status_#{task.status}") 
        td = task.end_date.try(:strftime, "%Y年%m月%d日")
        td 
          = link_to t(".update"), edit_task_path(task),
            class: "btn btn-primary mr-3" if current_user.own?(task) || logged_in_as_admin?
          = link_to t(".destroy"), task, method: :delete, 
            data: { confirm: t(".confirm", task_name: task.name) },
            class: "btn btn-danger" if current_user.own?(task) || logged_in_as_admin?
.mb-3
  = paginate @tasks

app/views/tasks/new.html.slim
h1 = t ".title"


.nav.justify-content-end
  = link_to t(".index"), root_path, class: "nav-link"

= render "form", task: @task

app/views/tasks/show.html.slim
h1 = t ".title"

.nav.justify-content-end
  = link_to t(".index"), root_path, class: "nav-link"

table.table.table-hover
  tbody
    tr
      th = User.human_attribute_name("name")
      td = @task.user.name
    tr
      th = Task.human_attribute_name("name")
      td = @task.name
    tr
      th = Task.human_attribute_name("description")
      td = simple_format(@task.description, {}, wrapper_tag: "div")
    tr
      th = Task.human_attribute_name("priority")
      th = @task.priority
    tr
      th = Task.human_attribute_name("status")
      td = Task.human_attribute_name("status_#{@task.status}")
    tr
      th = Task.human_attribute_name("end_date")
      td = @task.end_date.try(:strftime, "%Y年%m月%d日 %H時%M分")
    tr
      th = Task.human_attribute_name("created_at")
      td = @task.created_at.try(:strftime, "%Y年%m月%d日 %H時%M分")
    tr
      th = Task.human_attribute_name("updated_at")
      td = @task.updated_at.try(:strftime, "%Y年%m月%d日 %H時%M分")
    tr
      th = t("label")
      td 
        - @task.labels.each do |label|
          span.badge.badge-primary = label.name
          |  
= link_to t(".update"), edit_task_path,
  class: "btn btn-primary mr-3" if current_user.own?(@task) || logged_in_as_admin?