config/routes.rb
Rails.application.routes.draw do
  resources :labels, only: %i[new create destroy]
  namespace :admin do
    root "users#index"
    resources :users, except: [:index, :show]
  end
  root to: "tasks#index"
  resources :tasks, except: :index do
    get "search", on: :collection
    get "label_search", on: :collection
  end
  resources :users, only: [:new, :show, :create]
  resource :session, only: [:create, :destroy]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  administrator   :boolean          default(FALSE), not null
#  email           :string           not null
#  name            :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#
class User < ApplicationRecord
  has_secure_password
  has_many :tasks, dependent: :destroy
  has_many :labels, dependent: :destroy
  
  validates :name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  after_save :only_administrator, on: :update
  before_destroy do
    throw :abort if User.where(administrator: true).count ==  1 && self.administrator?
  end

  def own?(task)
    self.id == task.user_id
  end

  private

  def only_administrator
    if User.where(administrator: true).count.zero?
      errors.add(:administrator, "のある者は最低１人必要です！")
      raise ActiveRecord::Rollback
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::Base
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all.includes(:tasks)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_root_path, notice: "「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def edit; end

  def update
    @user.assign_attributes(user_params)
    if @user.save
      redirect_to admin_root_path, notice: "「#{@user.name}」を変更しました。"
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_root_path, notice: "「#{@user.name}」を削除しました。"
    else
      redirect_to admin_root_path, alert: "削除できません。管理者権限のある者は最低１人必要です！"
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      :administrator,
    )
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_required, only: :show
  before_action :set_user, only: :show
  
  def new
    if current_user
      redirect_to root_path
    else
      @user = User.new
    end
  end

  def show
    if logged_in_as_admin? || @user == current_user
      render :show
    else
      redirect_to root_path
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      :administrator,
    )
  end

  def only_my_pege
    if User.find(params: id) != current_user.id
      redirect_to root_path
    end
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/admin/users/_form.html.slim
= form_with model: [:admin, user], local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :email
    = f.text_field :email, class: "form-control"
  .form-group
    = f.label :password
    = f.password_field :password, class: "form-control"
  .form-group
    = f.label :password_confirmation
    = f.password_field :password_confirmation, class: "form-control"
  .form-check
    = f.label :administrator, class: "form-check-label" do
      = f.check_box :administrator, class: "form-check-input"
      = t("admin")
  = f.submit nil, class: "btn btn-primary mt-2"

app/views/admin/users/edit.html.slim
h1 = t("edit")

= render "shared/errors", obj: @user

= render "form", user: @user

app/views/admin/users/index.html.slim
h1 管理者のトップページ

.row.justify-content-end
  = link_to t("new_link"), new_admin_user_path, class: "btn btn-primary", id: "admin_new_user"

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th = User.human_attribute_name("id")
      th = User.human_attribute_name("name")
      th = User.human_attribute_name("email")
      th = User.human_attribute_name("tasks_counts")
      th = User.human_attribute_name("administrator")
      th
  tbody
    - @users.each do |user|
      tr
        td = user.id
        td = link_to user.name, user
        td = user.email
        td = user.tasks.count
        td = user.administrator? ? "⭕️" : "❌"
        td
          = link_to t("edit_link"), edit_admin_user_path(user), id: "admin_edit"
          |  |  
          = link_to t("delete_link"), admin_user_path(user), method: :delete,
            data: { confirm: "本当に削除しますか？" }, id: "admin_delete"

app/views/admin/users/new.html.slim
h1 = t("new")

= render "shared/errors", obj: @user

= render "form", user: @user